#CONFIGURATION

progname = main
CFLAGS = -Wall -fopenmp
LDFLAGS = -fopenmp
LDLIBS = -lm

#TEMPLATE

sources := $(wildcard *.c)
objects := $(patsubst %.c,%.o,$(sources))
test_objects := $(patsubst %.c,%.o,$(wildcard *_test.c))
prog_objects := $(filter-out $(test_objects),$(objects))

$(progname): $(prog_objects)


#Source file dependencies

depend: $(sources)
	makedepend -- $(CFLAGS) -- -Y $^ 2> /dev/null


#Unit testing

test_binaries := $(patsubst %.c,%,$(wildcard *_test.c))

.PHONY: test
test: $(test_binaries)
	$(foreach test,$^,./$(test))

%_test: %_test.o $(filter-out $(progname).o,$(prog_objects))
	$(CC) $(LDFLAGS) $^ $(LDLIBS) -o $@


#Cleanup

.PHONY: clean
clean:
	rm -f *.d *.o *_test Makefile.bak


#Rules generated by makedepend
# DO NOT DELETE

dist.o: dist.h
main.o: simulation.h
pqueue.o: pqueue.h
pqueue_test.o: pqueue.h
simulation.o: dist.h pqueue.h simulation.h
